BACKGROUNDS = [
    {'class_name': "none-bg", 'thumbnail': "none.jpg", 'scaled': "none.png"},
    {'class_name': "ash-bg", 'thumbnail': "ash.jpg", 'scaled': "ash.png"},
    {'class_name': "bamboo-bg", 'thumbnail': "bamboo.jpg", 'scaled': "bamboo.png"},
    {'class_name': "birch-bg", 'thumbnail': "birch.jpg", 'scaled': "birch.png"},
    {'class_name': "cedar-bg", 'thumbnail': "cedar.jpg", 'scaled': "cedar.png"},
    {'class_name': "cement-bg", 'thumbnail': "cement.jpg", 'scaled': "cement.png"},
    {'class_name': "deck-bg", 'thumbnail': "deck.jpg", 'scaled': "deck.png"},
    {'class_name': "grass-bg", 'thumbnail': "grass.jpg", 'scaled': "grass.png"},
    {'class_name': "maple-bg", 'thumbnail': "maple.jpg", 'scaled': "maple.png"},
    {'class_name': "oak-bg", 'thumbnail': "oak.jpg", 'scaled': "oak.png"},
    {'class_name': "steel-bg", 'thumbnail': "steel.jpg", 'scaled': "steel.png"},
    {'class_name': "walnut-bg", 'thumbnail': "walnut.jpg", 'scaled': "walnut.png"},
    {'class_name': "teak-bg", 'thumbnail': "teak.jpg", 'scaled': "teak.png"},
    {'class_name': "zinc-bg", 'thumbnail': "zinc.jpg", 'scaled': "zinc.png"},
]
