# -*- coding: utf-8 -*-

# _lazy is just like _() except safe for multi-threaded code
# top level variables aren't thread safe and you can end up with
# en-US for part of the execution and fr for the next piece :/

from tower import ugettext as _
from tower import ugettext_lazy as _lazy

QUESTIONS = {1: _lazy(u'It\'s Friday, 4 pm, and you\'re planning your weekend on the Internet. Do you spend your afternoon:'),
             2: _lazy(u'Party time, and you get to dress up. Your fashion mantra is...'),
             3: _lazy(u'Your considerate dentist has a massive selection of reading material, and you\'ve got 30 minutes before your appointment. Do you read about: '),
             4: _lazy(u'There\'s a big political upheaval going on in your country. You leap into action and:'),
             5: _lazy(u'You run into a lost tourist, who asks you how to get to the airport - she only has an hour to make her flight. You respond by:'),
             6: _lazy(u'Guess what? Your office is flooded, so you get the day off work. A perfect day for: '),
             7: _lazy(u'It\'s your third date and your paramour is coming over for dinner. You\'ll:'),
             8: _lazy(u'Think fast: you run into an old co-worker who says "Hey, let\'s get together soon".  You reply: '),
             9: _lazy(u'You\'re taking an online personality quiz. It asks you to take an honest look at yourself and fill in what you see. You write "I am: '),
             10: _lazy(u'You find a wallet stuffed with lots of cash, but no ID. After thinking about it you decide to:'),
             11: _lazy(u'You\'re taking a vacation alone. Your destination:'),
             12: _lazy(u'A car towing a giant trailer signals that they need to merge in ahead of you. Do you:'),
             13: _lazy(u'Blackout! You were watching TV, but now you have to find something else to do. You light up some candles, then:'),
             14: _lazy(u'It\'s midnight. Your hard drive just died. You have an important presentation at 8 am. What now, hot shot?'),
             15: _lazy(u'Your company has a new policy - no social networking at work. You handle the situation by:'),
             16: _lazy(u'The Internet is what you make of it - from serious business to rapping grannies.  You make it yours by:'),
             17: _lazy(u'Online, you can be the life of the party or a virtual wallflower. How social is your network?'),
             18: _lazy(u'It\'s a perfect Spring day - birds are chirping, sun is shining, and you are:'),
             19: _lazy(u'You and the Internet are dating. How would you describe the relationship?'),
             20: _lazy(u'We all like to connect to this great big thing we call the Internet. Where do you do it, and how?'),
}

ANSWERS = {1: _lazy(u'Watching movie trailers and TV show previews.'),
           2: _lazy(u'Checking out avalanche warnings for your backcountry ski trip.'),
           3: _lazy(u'Catching up with your friends\' status updates and tweets.'),
           4: _lazy(u'Emailing yourself work files so you can get more done by Monday.'),
           5: _lazy(u'I value tidiness and wield a mean steam iron.'),
           6: _lazy(u'I dress to impress, party or not.'),
           7: _lazy(u'It was on sale!'),
           8: _lazy(u'These socks match, right?'),
           9: _lazy(u'Pigmy giraffes of the Kalahari.'),
           10: _lazy(u'Hollywood\'s hottest couples reveal favorite colors.'),
           11: _lazy(u'2010\'s best 10,000rpm hard drives'),
           12: _lazy(u'None of the above - I prefer to stare blankly ahead. Straight ahead.'),
           13: _lazy(u'Take to Twitter and get the word out, avatar change and all.'),
           14: _lazy(u'Take action! Get off the Internet and into the voting booth.'),
           15: _lazy(u'Email your friends a form petition to sign.'),
           16: _lazy(u'Sit right back down. Activism is exhausting.'),
           17: _lazy(u'Shrugging your shoulders, feigning ignorance.'),
           18: _lazy(u'Looking up the shortest route on your smartphone, and getting her a cab.'),
           19: _lazy(u'Directing her to the nearest bus stop.'),
           20: _lazy(u'Getting your car, picking up her luggage and speeding to the airport.'),
           21: _lazy(u'Organizing a pick-up kickball game.'),
           22: _lazy(u'Sofa, slippers and sitcom reruns.'),
           23: _lazy(u'Finishing doctoral thesis, re-shingling roof, grooming both dogs, helping neighbor pave driveway, whittling some sticks,  learning C++, balancing gramophone turntable. '),
           24: _lazy(u'Planting perennial shade trees at the senior center.'),
           25: _lazy(u'Whip up some Coquilles Saint Jacques avec Pernod, with Gratin Dauphinois on the side.'),
           26: _lazy(u'Rehydrate a bowl of fancy ramen. (not the cheap cup!). '),
           27: _lazy(u'Email their parents so you can cook their favorite childhood food.'),
           28: _lazy(u'Peruse the local farmer\'s market for organic veggies.'),
           29: _lazy(u'We\'re going camping; you should totally come with, we have an extra sleeping bag. Yay!'),
           30: _lazy(u'Let\'s grab a cup of coffee, right now.'),
           31: _lazy(u'Right, I\'ll have my assistant schedule something. How\'s your Autumn looking?'),
           32: _lazy(u'Hey, we\'re together right now! Isn\'t that great?'),
           33: _lazy(u'A dynamic, successful go-getter everybody loves!'),
           34: _lazy(u'A regular person, just like everyone else.'),
           35: _lazy(u'Uncertain-let me ask a few people and I\'ll get back to you.'),
           36: _lazy(u'Me.'),
           37: _lazy(u'Search Craigslist to see if there\'s a reward offered.'),
           38: _lazy(u'Turn it over to the police.'),
           39: _lazy(u'Live large and party! It\'s your money now.'),
           40: _lazy(u'Donate it to your favorite charity.'),
           41: _lazy(u'Beach resort - I just want to relax and de-stress.'),
           42: _lazy(u'A group tour - I don\'t want to worry about the details.'),
           43: _lazy(u'Wherever the dart lands on the map.'),
           44: _lazy(u'Every country where there\'s a hostel - I\'m backpacking all year.'),
           45: _lazy(u'Speed up so you won\'t get stuck behind them.'),
           46: _lazy(u'Move over to the next lane; let someone else face this dilemma.'),
           47: _lazy(u'Slow down and wave them in. You can spare the 10 seconds.'),
           48: _lazy(u'Slowly pass them, wondering how they fit all those turnips in there.'),
           49: _lazy(u'Frantically look for batteries so you can at least listen to the radio.'),
           50: _lazy(u'Invite the neighbors over, light a fire, roast some marshmallows and sing camping songs all night.'),
           51: _lazy(u'Find a friend and play games that don\'t require electricity. Like chess.'),
           52: _lazy(u'Drive to the next town - oh sweet Wi-Fi, I\'ve found you!'),
           53: _lazy(u'Do the Handyman Special - fix the hard drive using doorbell wire, a lighter for soldering, some electrical tape, and tweezers from the hotel makeup kit.'),
           54: _lazy(u'Call the home office and whine to the IT guys.'),
           55: _lazy(u'Find an Internet cafe, use their computer to recreate the presentation.'),
           56: _lazy(u'Old school baby, markers and poster board. And red socks.'),
           57: _lazy(u'Sneak off to the restroom and tweet every 30 minutes. Colleagues think you have bladder issues.'),
           58: _lazy(u'Waiting until your lunch break, then updating your status.'),
           59: _lazy(u'Checking it at home in the evening - it can wait.'),
           60: _lazy(u'Whip out a pen and paper - it\'s time to go back to letter writing. '),
           61: _lazy(u'Simultaneously moving and shaking, as I make momentous financial decisions.'),
           62: _lazy(u'Delving into the vast array of knowledge, news, facts and figures, and even fictions that comprise the Internet\'s news structure.'),
           63: _lazy(u'Making dates, planning parties, keeping in touch with buddies and finding far-flung friends from the past. '),
           64: _lazy(u'Doing it all for the children- there\'s a whole world of resources out there that enrich my kids\' lives'),
           65: _lazy(u'Making art, both analog and digital, and sharing it with the world.'),
           66: _lazy(u'I\'ll log in to look up old high school friends or play some games, but I\'d rather pick up the phone for a chat.'),
           67: _lazy(u'With as many friends as I\'ve got, keeping in touch is easier online than in real life.'),
           68: _lazy(u'I\'m mayor of my own life - it would grind to a halt without the constant updates, tweets and check-ins.'),
           69: _lazy(u'Social what now? I\'ve never even signed on to MyBook or FacePlace or whatever.'),
           70: _lazy(u'Out in the park! I might check my bank account on my phone, but the Internet is the last thing on my mind.'),
           71: _lazy(u'At a ballgame! Talking sports with my friends, both at the game and online.'),
           72: _lazy(u'At home, posting the weather on Facebook while checking movie times for later, reading reviews, watching trailers... when does the sun go down again? Let me check on the Internet!'),
           73: _lazy(u'You mean birds are tweeting, right? I follow @birds. And no, I can\'t go out right now - I\'m reading a hilarious flamewar thread on Slashdot.'),
           74: _lazy(u'Casual Encounter. We meet up here and there for a good time or a laugh, but no sleepovers - I\'m an independent person.'),
           75: _lazy(u'Going steady. I can take a day or two on my own, but usually we\'re together, shopping or goofing around.'),
           76: _lazy(u'Long-term Relationship. The Internet is my soul-mate, the only one who really gets me, who doesn\'t laugh at my cats-on-their-backs photo obsession.'),
           77: _lazy(u'It\'s an addiction - I\'m taking classes to ease my co-dependency. Online classes.'),
           78: _lazy(u'Tethered to my desk, at work and at home.'),
           79: _lazy(u'I enjoy a balanced Internet diet - some desktop, some mobile.'),
           80: _lazy(u'I\'m an active sort, so mostly mobile,with a sprinkling of desktop when I need a rest.'),
           81: _lazy(u'Every device I have connects to the Internet all the time. Including my toaster.'),
}

ANSWERS_BY_IMAGE = {1: _lazy(u'One symbol stands above all others as the authority - wise, unquestionable, and universally fair. Want the truth? Look to The Cookie - The Cookie tells all.'),
                    2: _lazy(u'Fortune is yours, with this Omamori. You know that the best luck is the luck you carry with you, and having a guide sure can help.'),
                    3: _lazy(u'The Fortune Teller, The Cootie Catcher - an ancient, noble device of truth-seekers. Let fortunes be told forthrightly, with simple honesty guided by blind chance.'),
                    4: _lazy(u'Eat my dust! I\'m bumping up my browsing into hyperdrive and leaving lesser browsers behind.'),
                    5: _lazy(u'Mystery, science, adventure - these aspects of your character are embodied in your symbol - The Gyroscope. You have the unique ability to remain calm and steady as the world spins around you. Maybe you even know how to pirouette.'),
                    6: _lazy(u'You have drawn The Compass, for you know which way is up. Looking for adventure and whatever comes your way, you\'re as prepared as a scout and as bold as a pioneer.'),
                    7: _lazy(u'You shine brightly, illuminating the Internet ahead with a glow of knowledge and spirit of exploration. That\'s why you have drawn the Flashlight - symbol of the intrepid.'),
                    8: _lazy(u'You have drawn the Mark of the Connection; Active, strong and reliable - that\'s you. People count on you to keep grounded at all times, even up in the air.'),
                    9: _lazy(u'The Friendship Pin - an unbreakable bond between you and your BFF. It shows you are loyal, willing to wear your love on your sleeve (or sneaker).'),
                    10: _lazy(u'Your buddies will be overjoyed to learn that you\'ve drawn the Friendship Bracelet. It stands for sociability and your talent for making each friend, online and off, feel special. So very special.'),
                    11: _lazy(u'You have a bright outlook, flexible attitude, and a kooky sense of aesthetics. You\'re probably the type of person that appreciates the use of the word "kooky".'),
                    12: _lazy(u'Who are you, really? that\'s something you can decide, and decide again, and again. Create a persona for each world you live in. Just don\'t get confused, or they\'ll make a movie about you.'),
                    13: _lazy(u'The mark of the professional - you\'ve defined yourself in the business world, and earned a fancy title for your efforts.'),
                    14: _lazy(u'From wee tot or a genuine grown-up, building blocks captivate our imagination. To you a simple block is the first step towards works of beauty and grace. Also, you like toys.'),
                    15: _lazy(u'Appearances are not limited to the visible sphere - you are well aware of that, for you are The Aesthete. Beauty in every sense is your lofty goal, and no detail of that is too small to escape your scrutiny.'),
                    16: _lazy(u'The Locket - a secret treasured keepsake - is your symbol. Worn over the heart, it shows you value your relationships, and keep them close.'),
                    17: _lazy(u'It\'s just a matter of time - to you that\'s not a dismissive phrase, because you know how important it is to stick to a schedule. Precise and reliable, you appreciate the reassuring tick of a well-run machine.'),
                    18: _lazy(u'A sign of pluck and resourcefulness, a keen eye. The Button, both a tool and a decoration. You\'re equally multi-faceted.'),
                    19: _lazy(u'Vanity has not prevented you from making sure your vision of the world is crystal clear, and for that we bestow the symbol of The Glasses upon you. It shows that while your foresight might not always be perfect, your hindsight is 20/20.'),
                    20: _lazy(u'It\'s just a matter of time - to you that\'s not a dismissive phrase, because you know how important it is to stick to a schedule. Precise and reliable, you appreciate the reassuring tick of a well-run machine.'),
                    21: _lazy(u'\'Beauty is not in the face; beauty is a light in the heart\' said the poet Kahlil Gibran. But he never had to deal with high definition video. You are The Illusionist - master of your own appearance, poet of the eyeliner pen.'),
                    22: _lazy(u'Why, look at you. Clearly, you bear the mark of The Fierce. You know what\'s hot, but rock your own style, and can dance on that fine line that separates dandy from dowdy.'),
                    23: _lazy(u'Ancient symbol of self-reliance, the Knitting Needle stands for your expressive individuality in the face of commercialism. With your own hands you create that which you desire, and make it purely your own.'),
                    24: _lazy(u'Your future is bright.'),
                    25: _lazy(u'You\'ve earned The Comb! A mark of neatness that exemplifies your dedication to presenting a pleasing visage to the world. You\'ve got style, and substance too.'),
                    26: _lazy(u'You\'ve earned The Headphones. You know that the best concerts are the all-star lineups you stage for yourself, in your own head.'),
                    27: _lazy(u'Are these the ones that eat eucalyptus, or bamboo? Well, they\'re cute either way.'),
                    28: _lazy(u'The pachyderm - symbol of endless memory. Of course, this is a finger puppet, so it\'s really a symbol of a symbol. But that\'s semantics. Sorta cute, huh? '),
                    29: _lazy(u'Why, look at you. Clearly, you bear the mark of The Fierce. You know what\'s hot, but rock your own style, and can dance on that fine line that separates dandy from dowdy.'),
                    30: _lazy(u'You know what\'s next; you have it all written down in your date book -the symbol of The Organizer. You\'re the one we turn to when we are in doubt, for you hold the answers.'),
                    31: _lazy(u'You are the Gear Head - mark of those who know their limited-slip differential from their throttle body. You get all revved up at the sound of a big V8, and the smell of burning rubber brings a wistful tear to your eye.'),
                    32: _lazy(u'You know what /. means, and can tell a 404 from a 509. You\'re the one friends turn to when they need to know what\'s the new hot device. Geek? Yes, some call you that, but you are worthy of a far more majestic moniker, for you are The Technologist!'),
                    33: _lazy(u'You\'re in good company - beloved by visionaries before you, the little notebook says you know how to express yourself and keep it buttoned up at the same time. You know the best experiences deserve a record.'),
                    34: _lazy(u'Naughty, naughty! Your pursuit of [CENSORED] is [CENSORED], and. you\'re unafraid to cross new boundaries in search of [CENSORED] and [CENSORED].'),
                    35: _lazy(u'Endowed with unprecedented imaginative powers, you transport yourself to an alternate universe where you have X-ray vision, super strength, and some snazzy tights.'),
                    36: _lazy(u'The symbol of unpretentious creativity and art. You are almost certainly imbued with a child-like curiosity and an unfettered imagination, enjoy self expression and bright colors. You are child-like, or may actually be a child.'),
                    37: _lazy(u'For you, the Internet cannot be contained to a desk or a cafe. You carry it with you, not a place you go, but a tool you use. This is your Swiss Army Knife™.'),
                    38: _lazy(u'Everything\'s better with a monkey in it. Monkeys are fun, smart, and optimistic. You got this crafty monkey because it reflects your own delightful optimism and playfulness. Or maybe you like bananas?'),
                    39: _lazy(u'Take part, or take your seat. Political activism rewards those who participate and do something. You use the Internet as both to listen and to shout - and the world is better for it.'),
                    40: _lazy(u'You\'ve earned the harmonica, a silver badge of self-expression. You take life\'s lemons and turn them into melodious, slightly buzzy lemonade.'),
                    41: _lazy(u'The Lighter - a pocket-sized torch of freedom. It presages your preparedness for whatever crosses your path, be it a camper with a bunch of moist twigs, or some guy with a cigar.'),
                    42: _lazy(u'The written word is a powerful tool, whether it\'s typed in a blog or scrawled on a wall. You understand this power and you wield it with authority.'),
                    43: _lazy(u'The stamp - ubiquitous symbol of communication, of correspondence, which you\'ve earned. If you have these, you most likely checked your email halfway through reading this.'),
                    44: _lazy(u'The stamp - ubiquitous symbol of communication, of correspondence, which you\'ve earned. If you have these, you most likely checked your email halfway through reading this.'),
                    45: _lazy(u'PARTY! You got The Noisemaker! You make life a constant party that rocks the house and wakes up the neighbors - then invites them over. Everybody\'s having fun when you\'re around.'),
                    46: _lazy(u'Dust in the wind, man. Dust in the wind.'),
                    47: _lazy(u'"Seriousness is the only refuge of the shallow." - Oscar Wilde                                                                                                                                         '),
                    48: _lazy(u'There are times when you need to express your inner music, even if you don\'t know how to play an instrument. Sometimes all you need to do is hum along.'),
                    49: _lazy(u'Sometimes you just gotta be slick and superficial. We can\'t go around being deep and cerebral all the time, after all.'),
                    50: _lazy(u'Are these the ones that eat eucalyptus, or bamboo? Well, they\'re cute either way.'),
                    51: _lazy(u'For you, the Internet cannot be contained to a desk or a cafe. You carry it with you, not a place you go, but a tool you use. This is your Swiss Army Knife™.'),
                    52: _lazy(u'You have drawn The Compass, for you know which way is up. Looking for adventure and whatever comes your way, you\'re as prepared as a scout and as bold as a pioneer.'),
                    53: _lazy(u'You know what /. means, and can tell a 404 from a 509. You\'re the one friends turn to when they need to know what\'s the new hot device. Geek? Yes, some call you that, but you are worthy of a far more majestic moniker, for you are The Technologist!'),
                    54: _lazy(u'Eat my dust! I\'m bumping up my browsing into hyperdrive and leaving lesser browsers behind.'),
                    55: _lazy(u'The symbol of travel, of paths taken and untaken, of sleeping upright in a middle seat. You are The Traveler.'),
                    56: _lazy(u'The adhesive bandage - mark of The Healer. You seek the perfection of the human form, or at least one less headache.'),
                    57: _lazy(u'You hold The Keys - and indeed, they are your symbol. Master of your domain, you come and go as you please, wherever you please. You have every password memorized, know every PIN by heart.'),
                    58: _lazy(u'The mark of perseverance and tireless effort. You just keep going and going; nothing tires you out and you seem to never run out of juice.'),
                    59: _lazy(u'You have drawn the Mark of the Connection; Active, strong and reliable - that\'s you. People count on you to keep grounded at all times, even up in the air.'),
                    60: _lazy(u'Let\'s go! You\'re not one to sit around; you like the active, positive and healthful, in body mind and spirit. And you have the sweaty wrists to prove it.'),
                    61: _lazy(u'Ah, the Flask - the party is wherever you are, Social Butterfly. You bring it, and you bring it in style. But you also know when to stop. Keep it classy, my sleek silver friend!'),
                    62: _lazy(u'Party time? Excellent! You are the breeze that blows through a summer evening with friends new and old. The Cocktail Swordsman - or woman - knows how to parry with these weapons of social mirth.'),
                    63: _lazy(u'Candy - manna of the gods, because gods don\'t get cavities. That\'s your symbol, for you are the Sweet One. You cannot resist quick, indulgent temptation, for you know the joy it brings.'),
                    64: _lazy(u'You have drawn the Mark of the Connection; Active, strong and reliable - that\'s you. People count on you to keep grounded at all times, even up in the air.'),
                    65: _lazy(u'An apt (if cliché) symbol for your ability to simultaneously check your email, post on someone\'s Wall, watch a movie trailer and Tweet about it. You\'re like a human one of these!'),
                    66: _lazy(u'You\'re the Multi-tasker, attacking multiple projects and sites simultaneously. You come prepared and always have the right tool for the job.'),
                    67: _lazy(u'For you, the Internet cannot be contained to a desk or a cafe. You carry it with you, not a place you go, but a tool you use. This is your Swiss Army Knife™.'),
                    68: _lazy(u'Go ahead and open up all the tabs you want- there\'s never a last call for browsing.'),
                    69: _lazy(u'Technology lives to serve, and you like your information portable, pocketable and sharable. That\'s how data becomes action, and gadgets become essential.'),
                    70: _lazy(u'Let\'s go! You\'re not one to sit around; you like the active, positive and healthful, in body mind and spirit. And you have the sweaty wrists to prove it.'),
                    71: _lazy(u'Ah, the Flask - the party is wherever you are, Social Butterfly. You bring it, and you bring it in style. But you also know when to stop. Keep it classy, my sleek silver friend!'),
                    72: _lazy(u'This is a symbol of a symbol, which makes it extra relevant to you. You look at this folded paper and see a crane - you know the power of imagination.'),
                    73: _lazy(u'Appearances are not limited to the visible sphere - you are well aware of that, for you are The Aesthete. Beauty in every sense is your lofty goal, and no detail of that is too small to escape your scrutiny.'),
                    74: _lazy(u'Candy - manna of the gods, because gods don\'t get cavities. That\'s your symbol, for you are the Sweet One. You cannot resist quick, indulgent temptation, for you know the joy it brings.'),
                    75: _lazy(u'Gum is not just a snack, it\'s a tiny rectangular activity. It demands participation and rewards you with freshness, if only for a fleeting moment.'),
                    76: _lazy(u'Is there anything more versatile, efficient and useful than a spork? The very word is a model of multitasking efficiency. It shows you like to handle lots of things at once, and take big bites. Chew well!'),
                    77: _lazy(u'You bear the Mark of Cereal. Sustenance in its simplest, most basic form. Compact, practical, tidy and filling - read into it all you like.'),
                    78: _lazy(u'Sweet, cool and fresh. That describes both you and your favorite indulgences - just a little trifle to brighten your day, as you invigorate the world around you.'),
                    79: _lazy(u'Behold, The Memory - life is your field of study. You hunger for new thinking, knowledge and information. You know how get it, and how to hold on to it.'),
                    80: _lazy(u'The instant memory, quickly frozen and indelibly saved. Yours is the nostalgic type, pouring over cherished images and captured moments.'),
                    81: _lazy(u'Technology lives to serve, and you like your information portable, pocketable and sharable. That\'s how data becomes action, and gadgets become essential.'),
                    82: _lazy(u'Your body is a temple, and you\'re its master. You wield all the tools you need to keep it going, and aren\'t afraid of a little research.'),
                    83: _lazy(u'Let\'s go! You\'re not one to sit around; you like the active, positive and healthful, in body mind and spirit. And you have the sweaty wrists to prove it.'),
                    84: _lazy(u'Your buddies will be overjoyed to learn that you\'ve drawn the Friendship Bracelet. It stands for sociability and your talent for making each friend, online and off, feel special. So very special.'),
                    85: _lazy(u'The Friendship Pin - an unbreakable bond between you and your BFF. It shows you are loyal, willing to wear your love on your sleeve (or sneaker).'),
                    86: _lazy(u'The mark of the professional - you\'ve defined yourself in the business world, and earned a fancy title for your efforts.'),
                    87: _lazy(u'Who are you? A mystery, an enigma, a chameleon that no one really knows. You know what you need to keep private, and what to show the outside world. Your identity is yours alone - wear them proudly, anonymous.'),
                    88: _lazy(u'Who has the right combination? You do, for you are the Lock Master - in control and buttoned down, you value security but know when to open up and let loose.'),
                    89: _lazy(u'You can hope to ward off evil with a rabbit\'s foot, or you can be more proactive. You\'re the pragmatist - you own your destiny, control your security and know the value of self-defense.'),
                    90: _lazy(u'Text coming...'),
                    91: _lazy(u'You\'re a social vector - verily, you are goal-oriented, outgoing and bold. At last, you\'ve collected that number, and you\'re gonna use it.'),
                    92: _lazy(u'Who are you, really? that\'s something you can decide, and decide again, and again. Create a persona for each world you live in. Just don\'t get confused, or they\'ll make a movie about you.'),
                    93: _lazy(u'Your buddies will be overjoyed to learn that you\'ve drawn the Friendship Bracelet. It stands for sociability and your talent for making each friend, online and off, feel special. So very special.'),
                    94: _lazy(u'The Friendship Pin - an unbreakable bond between you and your BFF. It shows you are loyal, willing to wear your love on your sleeve (or sneaker).'),
                    95: _lazy(u'Your symbol is Ketchup - everybody loves it, gotta have some, it makes everything better. Just like you!'),
                    96: _lazy(u'You define your own treasures, and know their value lies deep in your heart. Either that or you look it up online.'),
                    97: _lazy(u'"Beauty is not in the face; beauty is a light in the heart" said the poet Kahlil Gibran. But he never had to deal with high definition video. You are The Illusionist - master of your own appearance, poet of the eyeliner pen.'),
                    98: _lazy(u'Who are you? A mystery, an enigma, a chameleon that no one really knows. You know what you need to keep private, and what to show the outside world. Your identity is yours alone - wear them proudly, anonymous.'),
                    99: _lazy(u'This vessel of curative liquid is your symbol, o power user! You are clear of vision, attack a problem at its source, and at the ready. You probably spend a lot of time staring at a screen, too.'),
                    100: _lazy(u'Craft your own world and it\'s exactly as you wish it to be. That is your secret - the secret of The Tailor. You make real that which most can only imagine, and edit the world to suit your taste.'),
                    101: _lazy(u'Wield the tools to make it yours, for you are unique - and your browser can reflect that.'),
                    102: _lazy(u'Ah, the quest for knowledge, the search for truth! To you life is a never-ending lesson, and you learn more and more each day. Or maybe you just do the crossword.'),
                    103: _lazy(u'One symbol stands above all others as the authority - wise, unquestionable, and universally fair. Want the truth? Look to The Cookie - The Cookie tells all.'),
                    104: _lazy(u'The mark of Money represents ability, utility and power. It\'s what people really mean when they say "resources" '),
                    105: _lazy(u'As easy as clapping on a light, it\'s what you\'ve been waiting for- the one-click bookmark. Don\'t you have enough to do without having to suffer the indignity of multiple clicks? '),
                    106: _lazy(u'Aha, The Magician! You posses unusual powers, and can conjure up the truth from any situation. Also, you can turn the world on with your smile.'),
                    107: _lazy(u'Infinite kindness and fortune, they smile upon you. You\'re searches lead you to answers, and you\'re feeling lucky.'),
                    108: _lazy(u'The Fortune Teller, The Cootie Catcher - an ancient, noble device of truth-seekers. Let fortunes be told forthrightly, with simple honesty guided by blind chance.'),
                    109: _lazy(u'Everything\'s better with a monkey in it. Monkeys are fun, smart, and optimistic. You got this crafty monkey because it reflects your own delightful optimism and playfulness. Or maybe you like bananas?'),
                    110: _lazy(u'Party time? Excellent! You are the breeze that blows through a summer evening with friends new and old. The Cocktail Swordsman - or woman - knows how to parry with these weapons of social mirth.'),
                    111: _lazy(u'A significant cultural heroic icon looms large in your inner nerd psyche. Embrace it. (We really don\'t want to get into the whole trademark thing, OK?)'),
                    112: _lazy(u'You reach into your past and explore the history that made you what you are. The letters, photos and mementos of the past are a mirror - they reflect the hopes and dreams that became today.'),
                    113: _lazy(u'The symbol of travel, of paths taken and untaken, of sleeping upright in a middle seat. You are The Traveler.'),
                    114: _lazy(u'You like to set a course for adventure, your mind on a new experience. Your treasured memories are your reward. Therefore you richly deserve The Nautilus!'),
                    115: _lazy(u'The instant memory, quickly frozen and indelibly saved. Yours is the nostalgic type, pouring over cherished images and captured moments.'),
                    116: _lazy(u'The cell phone - also called a mobile, for good reason. It represents you, Traveler - free and untethered, yet in touch wherever you may roam.'),
                    117: _lazy(u'Whether it\'s a cherished memento of a magical time or corny souvenir of a tacky holiday, you understand the value of your memories.'),
                    118: _lazy(u'The stamp - ubiquitous symbol of communication, of correspondence, which you\'ve earned. If you have these, you most likely checked your email halfway through reading this.'),
                    119: _lazy(u'The stamp - ubiquitous symbol of communication, of correspondence, which you\'ve earned. If you have these, you most likely checked your email halfway through reading this.'),
                    120: _lazy(u'You hold The Keys - and indeed, they are your symbol. Master of your domain, you come and go as you please, wherever you please. You have every password memorized, know every PIN by heart.'),
                    121: _lazy(u'You came, you saw, you captured! Always at the ready to preserve a moment, share it with the world, and tag photos of your friends.'),
                    122: _lazy(u'The photo strip, a talisman of remembrance and the nostalgia that goes along with it. You see value in conjuring the past and posting it to your Wall.'),
                    123: _lazy(u'The cell phone - also called a mobile, for good reason. It represents you, Traveler - free and untethered, yet in touch wherever you may roam.'),
                    124: _lazy(u'Entire worlds can be captured within a little sketchbook, worlds both real and imagined. You use many different tools to communicate your vision, Traveler.'),
                    125: _lazy(u'The world in all it\'s glorious flavors, aromas and textures, is your buffet. You delve into cuisines from neat and far, a traveler of the palette, a tourist with a deep-seated hunger. Feast, and all nations feast with you.'),
                    126: _lazy(u'You shine brightly, illuminating the Internet ahead with a glow of knowledge and spirit of exploration. That\'s why you have drawn the Flashlight - symbol of the intrepid.'),
                    127: _lazy(u'PARTY! You got The Noisemaker! You make life a constant party that rocks the house and wakes up the neighbors - then invites them over. Everybody\'s having fun when you\'re around.'),
                    128: _lazy(u'You believe the children are our future, and you want to raise them right. So you give them something to chew on , and something to think about.'),
                    129: _lazy(u'Everything\'s better with a monkey in it. Monkeys are fun, smart, and optimistic. You got this crafty monkey because it reflects your own delightful optimism and playfulness. Or maybe you like bananas?'),
                    130: _lazy(u'The instant memory, quickly frozen and indelibly saved. Yours is the nostalgic type, pouring over cherished images and captured moments.'),
                    131: _lazy(u'The adhesive bandage - mark of The Healer. You seek the perfection of the human form, or at least one less headache.'),
                    132: _lazy(u'What\'s next? you\'re never at a loss to answer that, because you\'ve planned what\'s next. Your organizational skills serve you well, and people count on you to get it done - right and on time.'),
                    133: _lazy(u'Behold, The Memory - life is your field of study. You hunger for new thinking, knowledge and information. You know how get it, and how to hold on to it.'),
                    134: _lazy(u'Technology lives to serve, and you like your information portable, pocketable and sharable. That\'s how data becomes action, and gadgets become essential.'),
                    135: _lazy(u'You know what\'s next; you have it all written down in your date book -the symbol of The Organizer. You\'re the one we turn to when we are in doubt, for you hold the answers.'),
                    136: _lazy(u'Behold The Fossil, lucky charm from ages long past! It symbolizes the truth of the past, and the search for knowledge in history (unless you clear your history).'),
                    137: _lazy(u'Dust in the wind, man. Dust in the wind.'),
                    138: _lazy(u'"Seriousness is the only refuge of the shallow." - Oscar Wilde                                                                                                                                         '),
                    139: _lazy(u'You believe the children are our future, and you want to raise them right. So you give them something to chew on , and something to think about.'),
                    140: _lazy(u'PARTY! You got The Noisemaker! You make life a constant party that rocks the house and wakes up the neighbors - then invites them over. Everybody\'s having fun when you\'re around.'),
                    141: _lazy(u'Are these the ones that eat eucalyptus, or bamboo? Well, they\'re cute either way.'),
                    142: _lazy(u'You are the Pet Whisperer! Play time to you is magnificent obsession, not mere diversion. You see the value of a faithful companion who will lick your face and lay on your keyboard.'),
                    143: _lazy(u'Everything\'s better with a monkey in it. Monkeys are fun, smart, and optimistic. You got this crafty monkey because it reflects your own delightful optimism and playfulness. Or maybe you like bananas?'),
                    144: _lazy(u'You are bright, optimistic, and careful when making a move - the very embodiment of Strategy. The world before you is as a game board, and you glide gracefully within it, taking and bringing joy.'),
                    145: _lazy(u'You make your own luck, for you know  fortune favors the fun loving! To you a day without a quick game is a day wasted. Life\'s too short to sulk, when you bear the colorful mark of The Player. (You\'re also possibly Chinese or a Grandmother)'),
                    146: _lazy(u'Sometimes the greatest in puzzles in life are solved in a few simple twists. We think you should turn your main finger topwise.'),
                    147: _lazy(u'Fun and games - they\'re just shy of everything to you. For that mirthful spirit, you are presented the mark of The Domino - symbolizing optimism, playfulness, and slamming things on tables.'),
                    148: _lazy(u'You like your fun and games on a cerebral level. Stretching your mind and beating your friends is as enjoyable to you as zoning out in front of the TV is to the hoi polloi.'),
                    149: _lazy(u'Ah, fickle chance. Who knows what a roll of the dice will bring. You live for the unknown - you look fortune straight in the eye and play the numbers she gives you.'),
                    150: _lazy(u'Rock show, film or sports match, you are there, live and in person. The thrill of being part of an event, not just observing it, is what you\'re after. You get tickets the second they go on sale and you have the stubs to prove it.'),
                    151: _lazy(u'You have a bright outlook, flexible attitude, and a kooky sense of aesthetics. You\'re probably the type of person that appreciates the use of the word "kooky".'),
                    152: _lazy(u'Text coming...'),
                    153: _lazy(u'You\'re in good company - beloved by visionaries before you, the little notebook says you know how to express yourself and keep it buttoned up at the same time. You know the best experiences deserve a record.'),
                    154: _lazy(u'An apt (if cliché) symbol for your ability to simultaneously check your email, post on someone\'s Wall, watch a movie trailer and Tweet about it. You\'re like a human one of these!'),
                    155: _lazy(u'You\'re the Multi-tasker, attacking multiple projects and sites simultaneously. you come prepared and always have the right tool for the job.'),
                    156: _lazy(u'The mark of Money represents ability, utility and power. It\'s what people really mean when they say "resources" '),
                    157: _lazy(u'The Lighter - a pocket-sized torch of freedom. It presages your preparedness for whatever crosses your path, be it a camper with a bunch of moist twigs, or some guy with a cigar.'),
                    158: _lazy(u'Is there anything more versatile, efficient and useful than a spork? The very word is a model of multitasking efficiency. It shows you like to handle lots of things at once, and take big bites. Chew well!'),
                    159: _lazy(u'The Lip Balm is your totem. Like a Boy Scout your motto is \'Be Prepared\'. You know what\'s important,  from looking good to protecting yourself.'),
                    160: _lazy(u'The adhesive bandage - mark of The Healer. You seek the perfection of the human form, or at least one less headache.'),
                    161: _lazy(u'An ounce of prevention carried in your pocket can be quite handy. You\'re prepared for those pesky little ailments that can crop up unexpectedly, and have the resources to deal with them. Gesundheit!'),
                    162: _lazy(u'Who are you? A mystery, an enigma, a chameleon that no one really knows. You know what you need to keep private, and what to show the outside world. Your identity is yours alone - wear them proudly, anonymous.'),
                    163: _lazy(u'The Pocket Knife - small, versatile, and just a little bit dangerous. It is your symbol because you are resourceful, and sharp, and you know how to fold yourself.'),
                    164: _lazy(u'This vessel of curative liquid is your symbol, o power user! You are clear of vision, attack a problem at its source, and at the ready. You probably spend a lot of time staring at a screen, too.'),
                    165: _lazy(u'You can hope to ward off evil with a rabbit\'s foot, or you can be more proactive. You\'re the pragmatist - you own your destiny, control your security and know the value of self-defense.'),
                    166: _lazy(u'Entire worlds can be captured within a little sketchbook, worlds both real and imagined. You use many different tools to communicate your vision, Traveler.'),
                    167: _lazy(u'A sign of pluck and resourcefulness, a keen eye. The Button, both a tool and a decoration. You\'re equally multi-faceted.'),
                    168: _lazy(u'The symbol of unpretentious creativity and art. You are almost certainly imbued with a child-like curiosity and an unfettered imagination, enjoy self expression and bright colors. You are child-like, or may actually be a child.'),
                    169: _lazy(u'The tool of the Artist; the world as your canvas. You see things not as they are, but as they could be, if you had a brush and a small cup of water.'),
                    170: _lazy(u'Ah, the Flask - the party is wherever you are, Social Butterfly. You bring it, and you bring it in style. But you also know when to stop. Keep it classy, my sleek silver friend!'),
                    171: _lazy(u'You\'ve earned The Headphones. You know that the best concerts are the all-star lineups you stage for yourself, in your own head.'),
                    172: _lazy(u'You can hope to ward off evil with a rabbit\'s foot, or you can be more proactive. You\'re the pragmatist - you own your destiny, control your security and know the value of self-defense.'),
                    173: _lazy(u'Internet Ninja! You leave no trace of your travels, online or off.'),
                    174: _lazy(u'Who has the right combination? You do, for you are the Lock Master - in control and buttoned down, you value security but know when to open up and let loose.'),
                    175: _lazy(u'Who are you? A mystery, an enigma, a chameleon that no one really knows. You know what you need to keep private, and what to show the outside world. Your identity is yours alone - wear them proudly, anonymous.'),
                    176: _lazy(u'Text coming...'),
                    177: _lazy(u'You\'re nothing if not a completist, and you like to take it with you. Compact, concise and in control, you are master of your musical domain. Mp3, WMA, FLAC - Rock accordingly.'),
                    178: _lazy(u'You have drawn the Mark of the Connection; Active, strong and reliable - that\'s you. People count on you to keep grounded at all times, even up in the air.'),
                    179: _lazy(u'You have drawn the Mark of the Connection; Active, strong and reliable - that\'s you. People count on you to keep grounded at all times, even up in the air.'),
                    180: _lazy(u'The written word is a powerful tool, whether it\'s typed in a blog or scrawled on a wall. You understand this power and you wield it with authority.'),
                    181: _lazy(u'You reach into your past and explore the history that made you what you are. The letters, photos and mementos of the past are a mirror - they reflect the hopes and dreams that became today.'),
                    182: _lazy(u'The mark of Money represents ability, utility and power. It\'s what people really mean when they say "resources" '),
                    183: _lazy(u'The mark of the professional - you\'ve defined yourself in the business world, and earned a fancy title for your efforts.'),
                    184: _lazy(u'You define your own treasures, and know their value lies deep in your heart. Either that or you look it up online.'),
                    185: _lazy(u'Oh Master of the Keys, only you have the password to the deepest dungeons of my online existence. Let\'s keep it that way.'),
                    186: _lazy(u'Ah, the quest for knowledge, the search for truth! To you life is a never-ending lesson, and you learn more and more each day. Or maybe you just do the crossword.'),
                    187: _lazy(u'You are The Reader. Your forte is seeking knowledge and delving into ideas, be they academic, scientific, or teenage vampire love stories.'),
                    188: _lazy(u'Endowed with imaginative powers lesser folks can\'t even comprehend. You tower above your peers. Chances are you have X-ray vision, super strength and an impressive collection of leggings'),
                    189: _lazy(u'As easy as clapping on a light, it\'s what you\'ve been waiting for- the one-click bookmark. Don\'t you have enough to do without having to suffer the indignity of multiple clicks? '),
                    190: _lazy(u'Text coming...'),
                    191: _lazy(u'You know what\'s next; you have it all written down in your date book -the symbol of The Organizer. You\'re the one we turn to when we are in doubt, for you hold the answers.'),
                    192: _lazy(u'PARTY! You got The Noisemaker! You make life a constant party that rocks the house and wakes up the neighbors - then invites them over. Everybody\'s having fun when you\'re around.'),
                    193: _lazy(u'The cell phone - also called a mobile, for good reason. It represents you, Traveler - free and untethered, yet in touch wherever you may roam.'),
                    194: _lazy(u'The cast-off talisman of a party shaman! You posses the strength and tenacity to turn the beat around, and you\'ve seen more sunrises from the wrong side of awake than any mere mortal.'),
                    195: _lazy(u'All is not lost! You can get back to where you once belonged, just by invoking the magical powers of Session Restore.'),
                    196: _lazy(u'From wee tot or a genuine grown-up, building blocks captivate our imagination. To you a simple block is the first step towards works of beauty and grace. Also, you like toys.'),
                    197: _lazy(u'Are these the ones that eat eucalyptus, or bamboo? Well, they\'re cute either way.'),
                    198: _lazy(u'You believe the children are our future, and you want to raise them right. So you give them something to chew on , and something to think about.'),
                    199: _lazy(u'The digital realm is your raw material, and you shape it into the wondrous things your mind\'s eye sees. (That\'s just about the most pretentious description of putty we could come up with.)'),
                    200: _lazy(u'Go ahead and open up all the tabs you want- there\'s never a last call for browsing.'),
                    201: _lazy(u'The tool of the Artist; the world as your canvas. You see things not as they are, but as they could be, if you had a brush and a small cup of water.'),
                    202: _lazy(u'The symbol of unpretentious creativity and art. You are almost certainly imbued with a child-like curiosity and an unfettered imagination, enjoy self expression and bright colors. You are child-like, or may actually be a child.'),
                    203: _lazy(u'Entire worlds can be captured within a little sketchbook, worlds both real and imagined. You use many different tools to communicate your vision, Traveler.'),
                    204: _lazy(u'Who are you, really? that\'s something you can decide, and decide again, and again. Create a persona for each world you live in. Just don\'t get confused, or they\'ll make a movie about you.'),
                    205: _lazy(u'The cell phone - also called a mobile, for good reason. It represents you, Traveler - free and untethered, yet in touch wherever you may roam.'),
                    206: _lazy(u'Fun and games - they\'re just shy of everything to you. For that mirthful spirit, you are presented the mark of The Domino - symbolizing optimism, playfulness, and slamming things on tables.'),
                    207: _lazy(u'You make your own luck, for you know  fortune favors the fun loving! To you a day without a quick game is a day wasted. Life\'s too short to sulk, when you bear the colorful mark of The Player. (You\'re also possibly Chinese or a Grandmother)'),
                    208: _lazy(u'You like your fun and games on a cerebral level. Stretching your mind and beating your friends is as enjoyable to you as zoning out in front of the TV is to the hoi polloi.'),
                    209: _lazy(u'Your buddies will be overjoyed to learn that you\'ve drawn the Friendship Bracelet. It stands for sociability and your talent for making each friend, online and off, feel special. So very special.'),
                    210: _lazy(u'The Friendship Pin - an unbreakable bond between you and your BFF. It shows you are loyal, willing to wear your love on your sleeve (or sneaker).'),
                    211: _lazy(u'You have a bright outlook, flexible attitude, and a kooky sense of aesthetics. You\'re probably the type of person that appreciates the use of the word "kooky".'),
                    212: _lazy(u'While some think a party means red plastic cups, you know that it can be an exquisite social event, a time to enjoy and strengthen friendships. What we\'re trying to say here is that you\'re a class act, even when you let loose.'),
                    213: _lazy(u'Oh Master of the Keys, only you have the password to the deepest dungeons of my online existence. Let\'s keep it that way.'),
                    214: _lazy(u'Mystery, science, adventure - these aspects of your character are embodied in your symbol - The Gyroscope. You have the unique ability to remain calm and steady as the world spins around you. Maybe you even know how to pirouette.'),
                    215: _lazy(u'It\'s just a matter of time - to you that\'s not a dismissive phrase, because you know how important it is to stick to a schedule. Precise and reliable, you appreciate the reassuring tick of a well-run machine.'),
                    216: _lazy(u'It\'s just a matter of time - to you that\'s not a dismissive phrase, because you know how important it is to stick to a schedule. Precise and reliable, you appreciate the reassuring tick of a well-run machine.'),
                    217: _lazy(u'For you, the Internet cannot be contained to a desk or a cafe. You carry it with you, not a place you go, but a tool you use. This is your Swiss Army Knife™.'),
                    218: _lazy(u'Eat my dust! I\'m bumping up my browsing into hyperdrive and leaving lesser browsers behind.'),
                    219: _lazy(u'Behold The Fossil, lucky charm from ages long past! It symbolizes the truth of the past, and the search for knowledge in history (unless you clear your history).'),
                    220: _lazy(u'If music be the food of love, a good mixtape represents a buffet of delectable morsels. Your love of different styles, and your ability to remix them to your personal soundtrack, earns you this totem'),
                    221: _lazy(u'You define your own treasures, and know their value lies deep in your heart. Either that or you look it up online.'),
                    222: _lazy(u'You have drawn the Mark of the Connection; Active, strong and reliable - that\'s you. People count on you to keep grounded at all times, even up in the air.'),
                    223: _lazy(u'Energy, nutrition, health - those are the things you value. It\'s good that you also like chocolate, otherwise you\'d be too boring to be anointed with the EnergyBar - a sophisticated melange of sporting intentions wrapped in a candy-like execution.'),
                    224: _lazy(u'Let\'s go! You\'re not one to sit around; you like the active, positive and healthful, in body mind and spirit. And you have the sweaty wrists to prove it.'),
                    225: _lazy(u'Rock show, film or sports match, you are there, live and in person. The thrill of being part of an event, not just observing it, is what you\'re after. You get tickets the second they go on sale and you have the stubs to prove it.'),
                    226: _lazy(u'You shine brightly, illuminating the Internet ahead with a glow of knowledge and spirit of exploration. That\'s why you have drawn the Flashlight - symbol of the intrepid.'),
                    227: _lazy(u'For you, the Internet cannot be contained to a desk or a cafe. You carry it with you, not a place you go, but a tool you use. This is your Swiss Army Knife™.'),
                    228: _lazy(u'Eat my dust! I\'m bumping up my browsing into hyperdrive and leaving lesser browsers behind.'),
                    229: _lazy(u'A symbol of risk and reward! You\'re no stranger to chance, to taking a walk on the 20-sided dark side. In the game of life, you\'re +10 Geekiness.'),
                    230: _lazy(u'A significant cultural heroic icon looms large in your inner nerd psyche. Embrace it. (We really don\'t want to get into the whole trademark thing, OK?)'),
                    231: _lazy(u'Is this a dream? Is this real life?'),
                    232: _lazy(u'You\'re a social vector - verily, you are goal-oriented, outgoing and bold. At last, you\'ve collected that number, and you\'re gonna use it.'),
                    233: _lazy(u'The cast-off talisman of a party shaman! You posses the strength and tenacity to turn the beat around, and you\'ve seen more sunrises from the wrong side of awake than any mere mortal.'),
                    234: _lazy(u'The Friendship Pin - an unbreakable bond between you and your BFF. It shows you are loyal, willing to wear your love on your sleeve (or sneaker).'),
                    235: _lazy(u'Your buddies will be overjoyed to learn that you\'ve drawn the Friendship Bracelet. It stands for sociability and your talent for making each friend, online and off, feel special. So very special.'),
                    236: _lazy(u'A connector! Binding together your tasks, your to-dos, your dreams and your desires. Connectors are useful things - hang on to it.'),
                    237: _lazy(u'You have drawn the Mark of the Connection; Active, strong and reliable - that\'s you. People count on you to keep grounded at all times, even up in the air.'),
                    238: _lazy(u'Behold, The Memory - life is your field of study. You hunger for new thinking, knowledge and information. You know how get it, and how to hold on to it.'),
                    239: _lazy(u'Behold The Fossil, lucky charm from ages long past! It symbolizes the truth of the past, and the search for knowledge in history (unless you clear your history).'),
                    240: _lazy(u'The photo strip, a talisman of remembrance and the nostalgia that goes along with it. You see value in conjuring the past and posting it to your Wall.'),
                    241: _lazy(u'The cell phone - also called a mobile, for good reason. It represents you, Traveler - free and untethered, yet in touch wherever you may roam.'),
                    242: _lazy(u'Infinite kindness and fortune, they smile upon you. You\'re searches lead you to answers, and you\'re feeling lucky.'),
                    243: _lazy(u'When was the last time you aligned your chakras? You\'re supposed to do it every 3,000 miles.'),
                    244: _lazy(u'For you, the Internet cannot be contained to a desk or a cafe. You carry it with you, not a place you go, but a tool you use. This is your Swiss Army Knife™.'),
                    245: _lazy(u'Fortune is yours, with this Omamori. You know that the best luck is the luck you carry with you, and having a guide sure can help.'),
                    246: _lazy(u'You have drawn the Mark of the Connection; Active, strong and reliable - that\'s you. People count on you to keep grounded at all times, even up in the air.'),
                    247: _lazy(u'For you, the Internet cannot be contained to a desk or a cafe. You carry it with you, not a place you go, but a tool you use. This is your Swiss Army Knife™.'),
                    248: _lazy(u'For you, the Internet cannot be contained to a desk or a cafe. You carry it with you, not a place you go, but a tool you use. This is your Swiss Army Knife™.'),
                    249: _lazy(u'Eat my dust! I\'m bumping up my browsing into hyperdrive and leaving lesser browsers behind.'),
}
